name: Github Actions simple node server
on:
  push:
    branches: [main]    
  pull_request:
    branches: [main]     

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

#uprawnienia potrzebne do jeśli wysyłane do ghcr.io
permissions: 
  contents: read
  packages: write


jobs:
  build-push-images:
    name: Budowa i publikacja obrazow na rozne architektury
    runs-on: ubuntu-latest
    steps:
       #Sprawdzenie kodu   
      - name: Checkout
        uses: actions/checkout@v2

      #ustawienie QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      # ustawienie Docker buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      #Ustawienie eksportu cache
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      #logowanie do Github container registry
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      

      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          file: ./zad1/Dockerfile
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
           #eksportowanie cache
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

          
      #przeniesienie cache do wskazanego folderu.
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
